#ifndef __SYSLOG_H__
#define __SYSLOG_H__

enum __syslog_action {
  SYSLOG_ACTION_CLOSE = 0,
  SYSLOG_ACTION_OPEN,
  SYSLOG_ACTION_READ,
  SYSLOG_ACTION_READ_ALL,
  SYSLOG_ACTION_READ_CLEAR,
  SYSLOG_ACTION_CLEAR,
  SYSLOG_ACTION_CONSOLE_OFF,
  SYSLOG_ACTION_CONSOLE_ON,
  SYSLOG_ACTION_CONSOLE_LEVEL,
  SYSLOG_ACTION_SIZE_UNREAD,
  SYSLOG_ACTION_SIZE_BUFFER,
};

int syslog(enum __syslog_action type, char *bufp, int len);

#endif  //__SYSLOG_H__

